name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Inject GCP Service Account Credentials
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > backend/app/service_config.json


      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_CONFIG_JSON }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Create .env and firebase config
        run: |
          echo -e "${{ secrets.ENV_BACKEND }}" > backend/.env
          echo '${{ secrets.FIREBASE_CONFIG_JSON }}' > backend/app/firebase_config.json

      - name: Build and push backend container
        run: |
          gcloud builds submit backend --tag gcr.io/$GCP_PROJECT/backend

      - name: Deploy backend to Cloud Run
        run: |
          gcloud run deploy educational-analyzer-api \
            --image gcr.io/$GCP_PROJECT/backend \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --port 8080

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
